{% set name = "phelel" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 307e1ca88ba04451c9f972feaf1ba97d24abe090191bac196c211a4c62d0de0f

build:
  entry_points:
    - phelel = phelel.scripts.phelel:run
    - phelel-load = phelel.scripts.phelel_load:run
    - velph = phelel.velph.cli.velph_cmd_root:cmd_root
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - phonopy >=3.0.1
    - phono3py >=3.27.1
    - finufft
    - click
    - tomli
    - tomli-w

test:
  imports:
    - phelel
  source_files:
    - test
  commands:
    - pip check
    - phelel --help
    - phelel-load --help
    - velph --help
    - pytest
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/phonopy/phelel
  description: |
    A code that provides a few computations needed to electron-phonon
    interaction calculation in finite-displacement method.
  summary: Finite-displacement electron-phonon code.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atztogo
